### ISSUE TITLE
Fidget Enhancements 

### ISSUE THREAD

**Issue by mx1001** [mx1001/Fidget#15]
Just brainstorming on enhancements for ensuring an easy user experience I have some ideas based on the current changes and updates in the nodes branch. 

![blender_2017-12-06_06-36-17](https://user-images.githubusercontent.com/15908237/33662383-321df64a-da51-11e7-88a3-74512819717e.png)

![image](https://user-images.githubusercontent.com/15908237/33662408-4546981c-da51-11e7-9ed4-026e25611a16.png)

I'm sure most of these ideas are no brainers that are predestined due to design based contexts but I just want to make sure they are mentioned somewhere. The preset conditional could be quite useful for getting into the tool very quickly or to deal with common situations in which you would want conditionals.

**Comment by niewinny** [comment]
the thing here is it's not really a menu, at least not in a way you think about it.
because of that, submenus cannot be created, nor the separation lines

I have an idea how I wanted to set that up, I am looking into some other problems first though

**Comment by proxeIO** [comment]
There is a template in Fidget/nodes/_[nodes.py](https://github.com/mx1001/Fidget/blob/aea4429691c476253245e2fa4c97068f3cb9a9cb/nodes/nodes.py)_ on line _[461](https://github.com/mx1001/Fidget/blob/aea4429691c476253245e2fa4c97068f3cb9a9cb/nodes/nodes.py#L461)_

By using that and/or adjusting the _node_categories_ list you can see the limitations with the add menu, it is possible to swap out the add menu with a _custom_ add menu.

Adding the _operator_ and _menu_ nodes that could be next on the agenda would offer prop_search for operators/menus available in blender, minus those that cannot be ran in the 3d view.

**Comment by niewinny** [comment]
thanks for the setup, I finally managed to make it work the way I wanted. #16 
It's not that important, so I think we can stick with that for now
